### ISSUE TITLE
liclipse failed if eclipse has been installed with shared jars via p2 

### ISSUE THREAD

**Issue by Sigi33** [fabioz/LiClipseText#23]
liclipse failed with the error message:

java.lang.NoClassDefFoundError: Could not initialize class org.brainwy.liclipsetext.editor.languages.tmbundle.parsing.TmSnippetParserV2

at org.brainwy.liclipsetext.editor.languages.tmbundle.parsing.TmSnippetParser.createReplacement(TmSnippetParser.java:52)
	at org.brainwy.liclipsetext.editor.languages.LanguagesManager.onSnippetFound(LanguagesManager.java:385)
	at org.brainwy.liclipsetext.editor.languages.LanguagesManager.loadTmBundle(LanguagesManager.java:311) 
....
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: **org/eclipse/swt/widgets/Display** [in thread "Worker-1: Decoration Calculation"]
	at org.eclipse.jface.text.rules.Token.prepareData(Token.java:82)
	at org.eclipse.jface.text.rules.Token.<init>(Token.java:83)

Eclipse has been installed as "shared" installation, where many of the jars are stored at **$HOME/.p2/pool**. 

Is there a fix for that issue or at least a workaround?

**Comment by fabioz** [comment]
This doesn't seem an issue in LiClipseText.

If `org/eclipse/swt/widgets/Display` cannot be found it's not something that can be solved in LiClipseText. There's some deeper issue in your installation as SWT should definitely be available.

i.e.: the dep is correct at https://github.com/fabioz/LiClipseText/blob/master/plugins/org.brainwy.liclipsetext.editor/META-INF/MANIFEST.MF#L9C2-L9C24.

So, closing the issue here (this is not solvable by LiClipseText).
